### ISSUE TITLE
What is the difference between this repo and star-pxl?

### ISSUE THREAD

**Issue by MustafaMustafa** [plexoos/star-pxl-test#1]

**Comment by plexoos** [comment]
Use star-bnl/star-pxl. In this one I just tried to fix committer names so that, for example, your commits exported from CVS can be properly recognized by git/github. Compare:
https://github.com/star-bnl/star-pxl/graphs/contributors
https://github.com/star-bnl/star-pxl-test/graphs/contributors

The problem is that CVS uses only usernames whereas git uses emails to identify the commit author. As you see it can be fixed but changes the SHA1's of each commit because the author name/email is used in SHA1 calculation. This fix would be needed to fix only the past commits but the future ones will be properly assigned to you if you use git as your primary repo. So, ignore this star-pxl-test repo please.

**Comment by plexoos** [comment]
I transferred this test repo to my personal page now so it does not confuse anyone

**Comment by MustafaMustafa** [comment]
Thank you very much for taking care of all of these issues.
